python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/run_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/run_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/run_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/enc_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/enc_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/enc_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/dec_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/dec_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/dec_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/both_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/both_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/baseline_g2t/both_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_finetune_g2t/tat_01_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_finetune_g2t/tat_01_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_finetune_g2t/tat_01_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_finetune_g2t/tat_02_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_finetune_g2t/tat_02_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_finetune_g2t/tat_02_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_finetune_g2t/tat_03_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_finetune_g2t/tat_03_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_finetune_g2t/tat_03_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/we0_01_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/we0_01_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/we0_01_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/we0_02_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/we0_02_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/we0_02_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/we0_03_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/we0_03_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/we0_03_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/0we_01_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/0we_01_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/0we_01_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/0we_02_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/0we_02_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/0we_02_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/0we_03_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/0we_03_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/0we_03_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/wewe_01_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/wewe_01_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/wewe_01_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/wewe_02_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/wewe_02_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/wewe_02_03 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/wewe_03_01 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/wewe_03_02 >> chrfs.txt
python calculate_metrics.py ../nmt-lse-es/lse_es_iSignos/thesis_exps/eslse/eslse_test_es_tok.txt -d ../nmt-lse-es/lse_es_iSignos/thesis_exps/runs/runs_features_g2t/wewe_03_03 >> chrfs.txt
